# Generated by Django 5.2.10 on 2026-01-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('file_path', models.CharField(default='', max_length=255)),
                ('visibility', models.BooleanField(default=False)),
            ],
        ),
    ]
