# Generated by Django 6.0.1 on 2026-03-27 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='repo_link',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
