# Generated by Django 6.0.1 on 2026-02-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repo_link',
            field=models.CharField(default='', max_length=255),
        ),
    ]
