# Generated by Django 6.0.1 on 2026-02-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_repo_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_edited',
            field=models.CharField(default='', max_length=10),
        ),
    ]
