# Generated by Django 6.0.1 on 2026-02-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_last_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='last_edited',
            field=models.DateField(auto_now=True),
        ),
    ]
