# Generated by Django 6.0.1 on 2026-02-08 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0004_project_repo_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('pk', models.CompositePrimaryKey('user_id', 'project_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('admin_perms', models.BooleanField(default=False)),
                ('edit_perms', models.BooleanField(default=False)),
                ('hours', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
