# Generated by Django 6.0.1 on 2026-03-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborator',
            name='pk',
        ),
        migrations.AddField(
            model_name='collaborator',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
