# Generated by Django 6.0.1 on 2026-04-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborator',
            name='color',
            field=models.CharField(default='#767676', max_length=7),
        ),
    ]
