# Generated by Django 6.0.1 on 2026-02-26 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_repo_link'),
        ('projectbranch', '0001_initial'),
        ('projectfiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfile',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='projectfile',
            name='repo_link',
        ),
        migrations.RemoveField(
            model_name='projectfile',
            name='visibility',
        ),
        migrations.AddField(
            model_name='projectfile',
            name='branch',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='projectbranch.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectfile',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project.project'),
            preserve_default=False,
        ),
    ]
