# Generated by Django 6.0.1 on 2026-03-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='password_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
