# Generated by Django 6.0.1 on 2026-03-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectbranch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='isMain',
            field=models.BooleanField(default=False),
        ),
    ]
