# Generated by Django 6.0.1 on 2026-03-26 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectbranch', '0002_branch_ismain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='isMain',
        ),
    ]
