# Generated by Django 6.0.1 on 2026-04-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectbranch', '0003_remove_branch_ismain'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='isMain',
            field=models.BooleanField(default=False),
        ),
    ]
