# Generated by Django 6.0.1 on 2026-04-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectbranch', '0004_branch_ismain'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='filepath',
            field=models.CharField(default='', max_length=255),
        ),
    ]
