# Generated by Django 6.0.1 on 2026-02-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectbrach', '0002_remove_branch_pk_branch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='isMain',
            field=models.BooleanField(default=False),
        ),
    ]
